### PR TITLE
Add build hook tests

### PR DESCRIPTION
**Pull request by mmafe**
# Summary of Changes
- Add test to run build trigger (stage) and confirm successful message appears
   - **Update:** Test now logs in as a publisher to test the build trigger
- Add test to confirm only publisher and administrator roles have access to build trigger
   - **Update:** Test now logs in as a publisher to check build hook is visible, then logs in as a user with all roles except publisher/administrator to check that access is denied.

## Build Results
- [drupal-8-composer Build with the Tests running successfully](https://dev.azure.com/uoguelph/CCS/_build/results?buildId=382&view=ms.vss-test-web.build-test-results-tab)
- [Gatsby Build triggered by test](https://dev.azure.com/uoguelph/CCS/_build/results?buildId=383&view=results)
- [Stage site that gets updated as a result of gatsby build](https://stageugconthub.uoguelph.dev/) vs the [Live site that hasn't been updated yet](https://liveugconthub.uoguelph.dev/)

### Is Content created by the story?
- [x] No
- [ ] If yes, the content is:
   - [ ] Accessible
   - [ ] Mobile-friendly
   - [ ] Version-controlled
   - [ ] Governed by appropriate roles and permissions
   - [ ] Organized by taxonomy

### Are there User-facing changes in the Drupal UI?
- [ ] No
- [x] If yes, then:
   - [x] User documentation is [updated](https://dev.azure.com/uoguelph/CCS/_git/wcm-content-hub-wiki?path=%2FUserDocumentation.md&version=GBmaster&_a=preview)
   - [ ] User training is updated **[No training exists yet]**

### Are there Upstream Code changes?
- [ ] No
- [x] If yes, then:
   - [x] Code is complete and commented.
   - [x] Code is secure to the best of our knowledge and does not contain anything that cannot be on a public repo (e.g. passwords)
   - Is a test necessary?
      - [ ] No
      - [x] If yes, then:
         - [x] Add a test if existing tests do not effectively test the code change
         - [x] Test passes
   - [x] Pull request (PR) is mergeable with *develop* branch
   - [x] PR has a meaningful title
   - [x] PR has a summary of changes
   - [ ] PR is peer reviewed and meets team standards.
   - [ ] PR builds without error

### CODE REVIEW

**Review by brharp — COMMENTED** [review]
Normally I would expect the permission test to log in as a user with a specific role, and then test for the correct permissions by asserting the button is on the page, or that clicking the button has the desired effect instead of inspecting the permissions page directly. Would that sort of test be possible here?

**Comment by mmafe** [comment]
@brharp I can probably rewrite the test in that manner. It would take more time to run the test, but it's probably doable. Did you want me to update the test so it also involves a publisher logging in and checking that the button is available?

Note that I would still need to somehow confirm that all other roles (besides publisher and administrator) do not have the permission. Rather than logging in as every other role and confirming that the role fails to access the button, I still believe it's more efficient to check via the permissions page that only publisher and administrator have the expected permissions. 

---

**Update:** The build hook is getting patched so it works for a release pipeline, so I'll be updating these tests anyway. In that case, I can work in any changes you'd like to see. I'll check in with you as I'm writing the tests (once the upstream patch is in place and the site config is updated).

**Comment by mmafe** [comment]
@brharp Updated the build trigger test so it logs in as a publisher prior to pressing the button. That way we can confirm the publisher is able to both see and trigger the button at the same time.

In order to confirm that ONLY publishers and administrators can view the button, I still left the second test so that it checks the permissions page. That way in future, if more roles are added, we don't have to attempt to log in as every single role. If you disagree, let me know and we can discuss.

One thing - I am wondering if we should create a "test" release pipe to use as the button trigger OR if we should leave it testing the real release build hook (a.k.a. the Preview Changes button). Right now it triggers the real build hook. Let me know if instead you want me to update it to trigger a "test" release pipeline instead.

**Comment by mmafe** [comment]
Note: I'm updating DrupalTest to include some of the more generic methods. Once the artifact appears on the uoguelph, I can update the tests so they call the generic methods from DrupalTest instead of including them in BoveyTest.

Although I don't think we need to wait to merge for that to happen since it could take a while for DrupalTest to show the latest artifact.

**Comment by brharp** [comment]
The tests worked for me.

I'm still not convinced that checking the permissions page is the best way to assert the correct permissions.  We don't need to test all other roles, we only need to make sure that if you have one of the required roles you can trigger the build, and if you do not have any of the required roles you cannot.

I have also seen Drupal tests that generate a role with the required permissions and use that for testing.

**Comment by mmafe** [comment]
@brharp Hey Brent, based on discussions yesterday, I've updated the tests as follows:
- **BuildHookSuccessful** logs in as publisher and tests the build hook
- **BuildHookOnlyVisibleForPublisherAndAdmin** logs in as a publisher and confirms build hook page is visible, then logs in as a user who has all roles except publisher/administrator and confirms access is denied.

I'm satisfied with this logic (and you convinced me about the usefulness of logging in for the tests). Let me know if both work for you and if you'd like to see any changes.

**Review by brharp — APPROVED** [review]
Looks good.

**Pull request merged**
